name: Cypress

on:
  push:
    branches:
      - 'main'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: ['chrome', 'firefox']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install root dependencies
        uses: bahmutov/npm-install@v1

      - name: Start server
        run: cp -a .env.example .env.local && yarn run dev &

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e
          browser: ${{ matrix.browser }}
          wait-on: 'http://localhost:3000'

      - name: Failure artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: e2e/cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos-${{ matrix.browser }}
          path: e2e/cypress/videos
